export default {
    state: {
        accessoriesMale: [
            {
                id:1,
                src:require('../../assets/Textures/Accessories/male/1.png'),
                posX:200,
                posY:200
            },
            {
                id:2,
                src:require('../../assets/Textures/Accessories/male/2.png'),
                posX:200,
                posY:200
            },
            {
                id:3,
                src:require('../../assets/Textures/Accessories/male/3.png'),
                posX:200,
                posY:200
            },
            {
                id:4,
                src:require('../../assets/Textures/Accessories/male/4.png'),
                posX:200,
                posY:200
            },
            {
                id:5,
                src:require('../../assets/Textures/Accessories/male/5.png'),
                posX:200,
                posY:200
            },
            {
                id:6,
                src:require('../../assets/Textures/Accessories/male/6.png'),
                posX:200,
                posY:200
            },
            {
                id:7,
                src:require('../../assets/Textures/Accessories/male/7.png'),
                posX:200,
                posY:200
            },
            {
                id:8,
                src:require('../../assets/Textures/Accessories/male/8.png'),
                posX:200,
                posY:200
            },
            {
                id:9,
                src:require('../../assets/Textures/Accessories/male/9.png'),
                posX:200,
                posY:200
            },
            {
                id:10,
                src:require('../../assets/Textures/Accessories/male/10.png'),
                posX:200,
                posY:200
            },
            {
                id:11,
                src:require('../../assets/Textures/Accessories/male/11.png'),
                posX:200,
                posY:200
            },
            {
                id:12,
                src:require('../../assets/Textures/Accessories/male/12.png'),
                posX:200,
                posY:200
            },
            {
                id:13,
                src:require('../../assets/Textures/Accessories/male/13.png'),
                posX:200,
                posY:200
            },
            {
                id:14,
                src:require('../../assets/Textures/Accessories/male/14.png'),
                posX:200,
                posY:200
            },
            {
                id: 15,
                src: null,
                posX: 200,
                posY: 200
            },
        ],
        accessoriesFemale: [
            {
                id:1,
                src:require('../../assets/Textures/Accessories/female/1.png'),
                posX:200,
                posY:200
            },
            {
                id:2,
                src:require('../../assets/Textures/Accessories/female/2.png'),
                posX:200,
                posY:200
            },
            {
                id:3,
                src:require('../../assets/Textures/Accessories/female/3.png'),
                posX:200,
                posY:200
            },
            {
                id:4,
                src:require('../../assets/Textures/Accessories/female/4.png'),
                posX:200,
                posY:200
            },
            {
                id:5,
                src:require('../../assets/Textures/Accessories/female/5.png'),
                posX:200,
                posY:200
            },
            {
                id:6,
                src:require('../../assets/Textures/Accessories/female/6.png'),
                posX:200,
                posY:200
            },
            {
                id:7,
                src:require('../../assets/Textures/Accessories/female/7.png'),
                posX:200,
                posY:200
            },
            {
                id:8,
                src:require('../../assets/Textures/Accessories/female/8.png'),
                posX:200,
                posY:200
            },
            {
                id:9,
                src:require('../../assets/Textures/Accessories/female/9.png'),
                posX:200,
                posY:200
            },
            {
                id:10,
                src:require('../../assets/Textures/Accessories/female/10.png'),
                posX:200,
                posY:200
            },
            {
                id:11,
                src:require('../../assets/Textures/Accessories/female/11.png'),
                posX:200,
                posY:200
            },
            {
                id:12,
                src:require('../../assets/Textures/Accessories/female/12.png'),
                posX:200,
                posY:200
            },
            {
                id:13,
                src:require('../../assets/Textures/Accessories/female/13.png'),
                posX:200,
                posY:200
            },
            {
                id:14,
                src:require('../../assets/Textures/Accessories/female/14.png'),
                posX:200,
                posY:200
            },
            {
                id:15,
                src:require('../../assets/Textures/Accessories/female/15.png'),
                posX:200,
                posY:200
            },
        ],
    }
}