export default {
    state: {
        accessoriesMale: [
            {
                id:1,
                src:require('../../assets/Textures/Accessories/male/1.png'),
                posX:406,
                posY:207,
                z:8
            },
            {
                id:2,
                src:require('../../assets/Textures/Accessories/male/2.png'),
                posX:420,
                posY:220,
                z:8
            },
            {
                id:3,
                src:require('../../assets/Textures/Accessories/male/3.png'),
                posX:408,
                posY:215,
                z:8
            },
            {
                id:4,
                src:require('../../assets/Textures/Accessories/male/4.png'),
                posX:463,
                posY:340,
                z:8
            },
            {
                id:5,
                src:require('../../assets/Textures/Accessories/male/5.png'),
                posX:350,
                posY:715,
                z:5
            },
            {
                id:6,
                src:require('../../assets/Textures/Accessories/male/6.png'),
                posX:641,
                posY:714,
                z:5
            },
            {
                id:7,
                src:require('../../assets/Textures/Accessories/male/7.png'),
                posX:410,
                posY:590,
                z:8
            },
            {
                id:8,
                src:require('../../assets/Textures/Accessories/male/8.png'),
                posX:419,
                posY:345,
                z:8
            },
            {
                id:9,
                src:require('../../assets/Textures/Accessories/male/9.png'),
                posX:419,
                posY:345,
                z:8
            },
            {
                id:10,
                src:require('../../assets/Textures/Accessories/male/10.png'),
                posX:622,
                posY:650,
                z:5
            },
            {
                id:11,
                src:require('../../assets/Textures/Accessories/male/11.png'),
                posX:463,
                posY:340,
                z:8
            },
            {
                id:12,
                src:require('../../assets/Textures/Accessories/male/12.png'),
                posX:463,
                posY:340,
                z:8
            },
            {
                id:13,
                src:require('../../assets/Textures/Accessories/male/13.png'),
                posX:363,
                posY:636,
                z:5
            },
            {
                id:14,
                src:require('../../assets/Textures/Accessories/male/14.png'),
                posX:620,
                posY:650,
                z:5
            },
            {
                id: 15,
                src: require('../../assets/question.png'),
                posX: -1000,
                posY: -1000,
                z:8
            },
        ],
        accessoriesFemale: [
            {
                id:1,
                src:require('../../assets/Textures/Accessories/female/1.png'),
                posX:555,
                posY:190,
                z:10
            },
            {
                id:2,
                src:require('../../assets/Textures/Accessories/female/2.png'),
                posX:555,
                posY:190,
                z:10
            },
            {
                id:3,
                src:require('../../assets/Textures/Accessories/female/3.png'),
                posX:494,
                posY:327,
                z:8
            },
            {
                id:4,
                src:require('../../assets/Textures/Accessories/female/4.png'),
                posX:492,
                posY:326,
                z:8
            },
            {
                id:5,
                src:require('../../assets/Textures/Accessories/female/5.png'),
                posX:490,
                posY:326,
                z:8
            },
            {
                id:6,
                src:require('../../assets/Textures/Accessories/female/6.png'),
                posX:510,
                posY:1050,
                z:4
            },
            {
                id:7,
                src:require('../../assets/Textures/Accessories/female/7.png'),
                posX:362,
                posY:714,
                z:6
            },
            {
                id:8,
                src:require('../../assets/Textures/Accessories/female/8.png'),
                posX:660,
                posY:710,
                z:6
            },
            {
                id:9,
                src:require('../../assets/Textures/Accessories/female/9.png'),
                posX:619,
                posY:625,
                z:6
            },
            {
                id:10,
                src:require('../../assets/Textures/Accessories/female/10.png'),
                posX:435,
                posY:365,
                z:8
            },
            {
                id:11,
                src:require('../../assets/Textures/Accessories/female/11.png'),
                posX:490,
                posY:317,
                z:8
            },
            {
                id:12,
                src:require('../../assets/Textures/Accessories/female/12.png'),
                posX:490,
                posY:325,
                z:8
            },
            {
                id:13,
                src:require('../../assets/Textures/Accessories/female/13.png'),
                posX:493,
                posY:325,
                z:8
            },
            {
                id:14,
                src:require('../../assets/Textures/Accessories/female/14.png'),
                posX:493,
                posY:325,
                z:8
            },
            {
                id:15,
                src:require('../../assets/Textures/Accessories/female/15.png'),
                posX:413,
                posY:570,
                z:8
            },
        ],
    }
}