export default {
    state: {
        // Мужские черные волосы
        hairBlackMale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/male/black/1.png')
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/male/black/2.png')
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/male/black/3.png')
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/male/black/4.png')
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/male/black/5.png')
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/male/black/6.png')
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/male/black/7.png')
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/male/black/8.png')
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/male/black/9.png')
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/male/black/10.png')
            }
        ],
        // Мужские коричнивые волосы
        hairBrownMale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/male/brown/1.png')
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/male/brown/2.png')
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/male/brown/3.png')
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/male/brown/4.png')
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/male/brown/5.png')
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/male/brown/6.png')
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/male/brown/7.png')
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/male/brown/8.png')
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/male/brown/9.png')
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/male/brown/10.png')
            }
        ],
        // Мужские темно-коричнивые волосы
        hairDarkBrownMale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/male/darkBrown/1.png')
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/male/darkBrown/2.png')
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/male/darkBrown/3.png')
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/male/darkBrown/4.png')
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/male/darkBrown/5.png')
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/male/darkBrown/6.png')
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/male/darkBrown/7.png')
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/male/darkBrown/8.png')
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/male/darkBrown/9.png')
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/male/darkBrown/10.png')
            }
        ],
        // Мужские рыжие волосы
        hairGingerMale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/male/ginger/1.png')
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/male/ginger/2.png')
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/male/ginger/3.png')
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/male/ginger/4.png')
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/male/ginger/5.png')
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/male/ginger/6.png')
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/male/ginger/7.png')
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/male/ginger/8.png')
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/male/ginger/9.png')
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/male/ginger/10.png')
            }
        ],
        // Мужские зеленые волосы
        hairGreenMale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/male/green/1.png')
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/male/green/2.png')
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/male/green/3.png')
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/male/green/4.png')
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/male/green/5.png')
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/male/green/6.png')
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/male/green/7.png')
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/male/green/8.png')
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/male/green/9.png')
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/male/green/10.png')
            }
        ],
        // Мужские серые волосы
        hairGreyMale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/male/grey/1.png')
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/male/grey/2.png')
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/male/grey/3.png')
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/male/grey/4.png')
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/male/grey/5.png')
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/male/grey/6.png')
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/male/grey/7.png')
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/male/grey/8.png')
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/male/grey/9.png')
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/male/grey/10.png')
            }
        ],
        // Мужские красные волосы
        hairRedMale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/male/red/1.png')
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/male/red/2.png')
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/male/red/3.png')
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/male/red/4.png')
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/male/red/5.png')
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/male/red/6.png')
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/male/red/7.png')
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/male/red/8.png')
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/male/red/9.png')
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/male/red/10.png')
            }
        ],
    },
}