export default {
    state: {
        // Женские черные волосы
        hairBlackFemale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/female/black/1.png'),
                posX:368,
                posY:129,
                z:10
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/female/black/2.png'),
                posX:415,
                posY:126,
                z:10
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/female/black/3.png'),
                posX:390,
                posY:123,
                z:10
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/female/black/4.png'),
                posX:401,
                posY:107,
                z:10
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/female/black/5.png'),
                posX:419,
                posY:130,
                z:10
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/female/black/6.png'),
                posX:414,
                posY:130,
                z:10
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/female/black/7.png'),
                posX:404,
                posY:110,
                z:10
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/female/black/8.png'),
                posX:415,
                posY:130,
                z:10
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/female/black/9.png'),
                posX:429,
                posY:109,
                z:10
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/female/black/10.png'),
                posX:407,
                posY:125,
                z:10
            },
            {
                id:'11',
                src:require('../../assets/Textures/Hair/female/black/12.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'12',
                src:require('../../assets/Textures/Hair/female/black/13.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'13',
                src:require('../../assets/Textures/Hair/female/black/14.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'14',
                src:require('../../assets/Textures/Hair/female/black/15.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'15',
                src:require('../../assets/Textures/Hair/female/black/22.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'16',
                src:require('../../assets/Textures/Hair/female/black/23.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'17',
                src:require('../../assets/Textures/Hair/female/black/24.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'18',
                src:require('../../assets/Textures/Hair/female/black/25.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'19',
                src:require('../../assets/Textures/Hair/female/black/21.png'),
                posX:413,
                posY:105,
                z:10
            },
            {
                id:'20',
                src:require('../../assets/Textures/Hair/female/black/31.png'),
                posX:408,
                posY:105,
                z:10
            },
        ],
        // Женские  бордовые волосы
        hairBordoFemale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/female/bordo/1.png'),
                posX:368,
                posY:129,
                z:10
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/female/bordo/2.png'),
                posX:415,
                posY:126,
                z:10
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/female/bordo/3.png'),
                posX:390,
                posY:123,
                z:10
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/female/bordo/4.png'),
                posX:401,
                posY:107,
                z:10
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/female/bordo/5.png'),
                posX:419,
                posY:130,
                z:10
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/female/bordo/6.png'),
                posX:414,
                posY:130,
                z:10
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/female/bordo/7.png'),
                posX:404,
                posY:110,
                z:10
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/female/bordo/8.png'),
                posX:415,
                posY:130,
                z:10
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/female/bordo/9.png'),
                posX:429,
                posY:109,
                z:10
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/female/bordo/10.png'),
                posX:407,
                posY:125,
                z:10
            },
            {
                id:'11',
                src:require('../../assets/Textures/Hair/female/bordo/12.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'12',
                src:require('../../assets/Textures/Hair/female/bordo/13.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'13',
                src:require('../../assets/Textures/Hair/female/bordo/14.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'14',
                src:require('../../assets/Textures/Hair/female/bordo/15.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'15',
                src:require('../../assets/Textures/Hair/female/bordo/22.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'16',
                src:require('../../assets/Textures/Hair/female/bordo/23.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'17',
                src:require('../../assets/Textures/Hair/female/bordo/24.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'18',
                src:require('../../assets/Textures/Hair/female/bordo/25.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'19',
                src:require('../../assets/Textures/Hair/female/bordo/21.png'),
                posX:413,
                posY:105,
                z:10
            },
            {
                id:'20',
                src:require('../../assets/Textures/Hair/female/bordo/31.png'),
                posX:408,
                posY:105,
                z:10
            },
        ],
        // Женские коричнивые волосы
        hairBrownFemale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/female/brown/1.png'),
                posX:368,
                posY:129,
                z:10
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/female/brown/2.png'),
                posX:415,
                posY:126,
                z:10
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/female/brown/3.png'),
                posX:390,
                posY:123,
                z:10
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/female/brown/4.png'),
                posX:401,
                posY:107,
                z:10
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/female/brown/5.png'),
                posX:419,
                posY:130,
                z:10
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/female/brown/6.png'),
                posX:414,
                posY:130,
                z:10
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/female/brown/7.png'),
                posX:404,
                posY:110,
                z:10
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/female/brown/8.png'),
                posX:415,
                posY:130,
                z:10
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/female/brown/9.png'),
                posX:429,
                posY:109,
                z:10
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/female/brown/10.png'),
                posX:407,
                posY:125,
                z:10
            },
            {
                id:'11',
                src:require('../../assets/Textures/Hair/female/brown/12.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'12',
                src:require('../../assets/Textures/Hair/female/brown/13.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'13',
                src:require('../../assets/Textures/Hair/female/brown/14.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'14',
                src:require('../../assets/Textures/Hair/female/brown/15.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'15',
                src:require('../../assets/Textures/Hair/female/brown/22.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'16',
                src:require('../../assets/Textures/Hair/female/brown/23.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'17',
                src:require('../../assets/Textures/Hair/female/brown/24.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'18',
                src:require('../../assets/Textures/Hair/female/brown/25.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'19',
                src:require('../../assets/Textures/Hair/female/brown/21.png'),
                posX:413,
                posY:105,
                z:10
            },
            {
                id:'20',
                src:require('../../assets/Textures/Hair/female/brown/31.png'),
                posX:408,
                posY:105,
                z:10
            },
        ],
        // Женские рыжие волосы
        hairGingerFemale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/female/ginger/1.png'),
                posX:368,
                posY:129,
                z:10
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/female/ginger/2.png'),
                posX:415,
                posY:126,
                z:10
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/female/ginger/3.png'),
                posX:390,
                posY:123,
                z:10
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/female/ginger/4.png'),
                posX:401,
                posY:107,
                z:10
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/female/ginger/5.png'),
                posX:419,
                posY:130,
                z:10
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/female/ginger/6.png'),
                posX:414,
                posY:130,
                z:10
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/female/ginger/7.png'),
                posX:404,
                posY:110,
                z:10
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/female/ginger/8.png'),
                posX:415,
                posY:130,
                z:10
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/female/ginger/9.png'),
                posX:429,
                posY:109,
                z:10
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/female/ginger/10.png'),
                posX:407,
                posY:125,
                z:10
            },
            {
                id:'11',
                src:require('../../assets/Textures/Hair/female/ginger/12.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'12',
                src:require('../../assets/Textures/Hair/female/ginger/13.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'13',
                src:require('../../assets/Textures/Hair/female/ginger/14.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'14',
                src:require('../../assets/Textures/Hair/female/ginger/15.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'15',
                src:require('../../assets/Textures/Hair/female/ginger/22.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'16',
                src:require('../../assets/Textures/Hair/female/ginger/23.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'17',
                src:require('../../assets/Textures/Hair/female/ginger/24.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'18',
                src:require('../../assets/Textures/Hair/female/ginger/25.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'19',
                src:require('../../assets/Textures/Hair/female/ginger/21.png'),
                posX:413,
                posY:105,
                z:10
            },
            {
                id:'20',
                src:require('../../assets/Textures/Hair/female/ginger/31.png'),
                posX:408,
                posY:105,
                z:10
            },
        ],
        // Женские зеленые волосы
        hairGreenFemale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/female/green/1.png'),
                posX:368,
                posY:129,
                z:10
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/female/green/2.png'),
                posX:415,
                posY:126,
                z:10
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/female/green/3.png'),
                posX:390,
                posY:123,
                z:10
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/female/green/4.png'),
                posX:401,
                posY:107,
                z:10
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/female/green/5.png'),
                posX:419,
                posY:130,
                z:10
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/female/green/6.png'),
                posX:414,
                posY:130,
                z:10
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/female/green/7.png'),
                posX:404,
                posY:110,
                z:10
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/female/green/8.png'),
                posX:415,
                posY:130,
                z:10
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/female/green/9.png'),
                posX:429,
                posY:109,
                z:10
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/female/green/10.png'),
                posX:407,
                posY:125,
                z:10
            },
            {
                id:'11',
                src:require('../../assets/Textures/Hair/female/green/12.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'12',
                src:require('../../assets/Textures/Hair/female/green/13.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'13',
                src:require('../../assets/Textures/Hair/female/green/14.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'14',
                src:require('../../assets/Textures/Hair/female/green/15.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'15',
                src:require('../../assets/Textures/Hair/female/green/22.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'16',
                src:require('../../assets/Textures/Hair/female/green/23.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'17',
                src:require('../../assets/Textures/Hair/female/green/24.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'18',
                src:require('../../assets/Textures/Hair/female/green/25.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'19',
                src:require('../../assets/Textures/Hair/female/green/21.png'),
                posX:413,
                posY:105,
                z:10
            },
            {
                id:'20',
                src:require('../../assets/Textures/Hair/female/green/31.png'),
                posX:408,
                posY:105,
                z:10
            },
        ],
        // Женские светло-коричнивые волосы
        hairLightBrownFemale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/female/lightBrown/1.png'),
                posX:368,
                posY:129,
                z:10
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/female/lightBrown/2.png'),
                posX:415,
                posY:126,
                z:10
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/female/lightBrown/3.png'),
                posX:390,
                posY:123,
                z:10
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/female/lightBrown/4.png'),
                posX:401,
                posY:107,
                z:10
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/female/lightBrown/5.png'),
                posX:419,
                posY:130,
                z:10
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/female/lightBrown/6.png'),
                posX:414,
                posY:130,
                z:10
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/female/lightBrown/7.png'),
                posX:404,
                posY:110,
                z:10
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/female/lightBrown/8.png'),
                posX:415,
                posY:130,
                z:10
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/female/lightBrown/9.png'),
                posX:429,
                posY:109,
                z:10
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/female/lightBrown/10.png'),
                posX:407,
                posY:125,
                z:10
            },
            {
                id:'11',
                src:require('../../assets/Textures/Hair/female/lightBrown/12.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'12',
                src:require('../../assets/Textures/Hair/female/lightBrown/13.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'13',
                src:require('../../assets/Textures/Hair/female/lightBrown/14.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'14',
                src:require('../../assets/Textures/Hair/female/lightBrown/15.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'15',
                src:require('../../assets/Textures/Hair/female/lightBrown/22.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'16',
                src:require('../../assets/Textures/Hair/female/lightBrown/23.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'17',
                src:require('../../assets/Textures/Hair/female/lightBrown/24.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'18',
                src:require('../../assets/Textures/Hair/female/lightBrown/25.png'),
                posX:407,
                posY:125,
                z:10
            },
            {
                id:'19',
                src:require('../../assets/Textures/Hair/female/lightBrown/21.png'),
                posX:413,
                posY:105,
                z:10
            },
            {
                id:'20',
                src:require('../../assets/Textures/Hair/female/lightBrown/31.png'),
                posX:408,
                posY:105,
                z:10
            },
        ],
        // Женские красные волосы
        hairRedFemale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/female/red/1.png'),
                posX:368,
                posY:129,
                z:10
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/female/red/2.png'),
                posX:415,
                posY:126,
                z:10
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/female/red/3.png'),
                posX:390,
                posY:123,
                z:10
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/female/red/4.png'),
                posX:401,
                posY:107,
                z:10
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/female/red/5.png'),
                posX:419,
                posY:130,
                z:10
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/female/red/6.png'),
                posX:414,
                posY:130,
                z:10
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/female/red/7.png'),
                posX:404,
                posY:110,
                z:10
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/female/red/8.png'),
                posX:415,
                posY:130,
                z:10
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/female/red/9.png'),
                posX:429,
                posY:109,
                z:10
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/female/red/10.png'),
                posX:407,
                posY:125,
                z:10
            },
            {
                id:'11',
                src:require('../../assets/Textures/Hair/female/red/12.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'12',
                src:require('../../assets/Textures/Hair/female/red/13.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'13',
                src:require('../../assets/Textures/Hair/female/red/14.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'14',
                src:require('../../assets/Textures/Hair/female/red/15.png'),
                posX:328,
                posY:107,
                z:10
            },
            {
                id:'15',
                src:require('../../assets/Textures/Hair/female/red/22.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'16',
                src:require('../../assets/Textures/Hair/female/red/23.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'17',
                src:require('../../assets/Textures/Hair/female/red/24.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'18',
                src:require('../../assets/Textures/Hair/female/red/25.png'),
                posX:328,
                posY:110,
                z:10
            },
            {
                id:'19',
                src:require('../../assets/Textures/Hair/female/red/21.png'),
                posX:413,
                posY:105,
                z:10
            },
            {
                id:'20',
                src:require('../../assets/Textures/Hair/female/red/31.png'),
                posX:408,
                posY:105,
                z:10
            },
        ],
    },
}