export default {
    state: {
        // Женские черные волосы
        hairBlackFemale:[
            {
                id:'1',
                src:'~@/assets/Textures/Hair/female/black/1.png'
            },
            {
                id:'2',
                src:'~@/assets/Textures/Hair/female/black/2.png'
            },
            {
                id:'3',
                src:'~@/assets/Textures/Hair/female/black/3.png'
            },
            {
                id:'4',
                src:'~@/assets/Textures/Hair/female/black/4.png'
            },
            {
                id:'5',
                src:'~@/assets/Textures/Hair/female/black/5.png'
            },
            {
                id:'6',
                src:'~@/assets/Textures/Hair/female/black/6.png'
            },
            {
                id:'7',
                src:'~@/assets/Textures/Hair/female/black/7.png'
            },
            {
                id:'8',
                src:'~@/assets/Textures/Hair/female/black/8.png'
            },
            {
                id:'9',
                src:'~@/assets/Textures/Hair/female/black/9.png'
            },
            {
                id:'10',
                src:'~@/assets/Textures/Hair/female/black/10.png'
            }
        ],
        // Женские  бордовые волосы
        hairBordoFemale:[
            {
                id:'1',
                src:'~@/assets/Textures/Hair/female/bordo/1.png'
            },
            {
                id:'2',
                src:'~@/assets/Textures/Hair/female/bordo/2.png'
            },
            {
                id:'3',
                src:'~@/assets/Textures/Hair/female/bordo/3.png'
            },
            {
                id:'4',
                src:'~@/assets/Textures/Hair/female/bordo/4.png'
            },
            {
                id:'5',
                src:'~@/assets/Textures/Hair/female/bordo/5.png'
            },
            {
                id:'6',
                src:'~@/assets/Textures/Hair/female/bordo/6.png'
            },
            {
                id:'7',
                src:'~@/assets/Textures/Hair/female/bordo/7.png'
            },
            {
                id:'8',
                src:'~@/assets/Textures/Hair/female/bordo/8.png'
            },
            {
                id:'9',
                src:'~@/assets/Textures/Hair/female/bordo/9.png'
            },
            {
                id:'10',
                src:'~@/assets/Textures/Hair/female/bordo/10.png'
            }
        ],
        // Женские коричнивые волосы
        hairBrownFemale:[
            {
                id:'1',
                src:'~@/assets/Textures/Hair/female/brown/1.png'
            },
            {
                id:'2',
                src:'~@/assets/Textures/Hair/female/brown/2.png'
            },
            {
                id:'3',
                src:'~@/assets/Textures/Hair/female/brown/3.png'
            },
            {
                id:'4',
                src:'~@/assets/Textures/Hair/female/brown/4.png'
            },
            {
                id:'5',
                src:'~@/assets/Textures/Hair/female/brown/5.png'
            },
            {
                id:'6',
                src:'~@/assets/Textures/Hair/female/brown/6.png'
            },
            {
                id:'7',
                src:'~@/assets/Textures/Hair/female/brown/7.png'
            },
            {
                id:'8',
                src:'~@/assets/Textures/Hair/female/brown/8.png'
            },
            {
                id:'9',
                src:'~@/assets/Textures/Hair/female/brown/9.png'
            },
            {
                id:'10',
                src:'~@/assets/Textures/Hair/female/brown/10.png'
            }
        ],
        // Женские рыжие волосы
        hairGingerfemale:[
            {
                id:'1',
                src:'~@/assets/Textures/Hair/female/ginger/1.png'
            },
            {
                id:'2',
                src:'~@/assets/Textures/Hair/female/ginger/2.png'
            },
            {
                id:'3',
                src:'~@/assets/Textures/Hair/female/ginger/3.png'
            },
            {
                id:'4',
                src:'~@/assets/Textures/Hair/female/ginger/4.png'
            },
            {
                id:'5',
                src:'~@/assets/Textures/Hair/female/ginger/5.png'
            },
            {
                id:'6',
                src:'~@/assets/Textures/Hair/female/ginger/6.png'
            },
            {
                id:'7',
                src:'~@/assets/Textures/Hair/female/ginger/7.png'
            },
            {
                id:'8',
                src:'~@/assets/Textures/Hair/female/ginger/8.png'
            },
            {
                id:'9',
                src:'~@/assets/Textures/Hair/female/ginger/9.png'
            },
            {
                id:'10',
                src:'~@/assets/Textures/Hair/female/ginger/10.png'
            }
        ],
        // Женские зеленые волосы
        hairGreenfemale:[
            {
                id:'1',
                src:'~@/assets/Textures/Hair/female/green/1.png'
            },
            {
                id:'2',
                src:'~@/assets/Textures/Hair/female/green/2.png'
            },
            {
                id:'3',
                src:'~@/assets/Textures/Hair/female/green/3.png'
            },
            {
                id:'4',
                src:'~@/assets/Textures/Hair/female/green/4.png'
            },
            {
                id:'5',
                src:'~@/assets/Textures/Hair/female/green/5.png'
            },
            {
                id:'6',
                src:'~@/assets/Textures/Hair/female/green/6.png'
            },
            {
                id:'7',
                src:'~@/assets/Textures/Hair/female/green/7.png'
            },
            {
                id:'8',
                src:'~@/assets/Textures/Hair/female/green/8.png'
            },
            {
                id:'9',
                src:'~@/assets/Textures/Hair/female/green/9.png'
            },
            {
                id:'10',
                src:'~@/assets/Textures/Hair/female/green/10.png'
            }
        ],
        // Женские светло-коричнивые волосы
        hairLightBrownfemale:[
            {
                id:'1',
                src:'~@/assets/Textures/Hair/female/lightBrown/1.png'
            },
            {
                id:'2',
                src:'~@/assets/Textures/Hair/female/lightBrown/2.png'
            },
            {
                id:'3',
                src:'~@/assets/Textures/Hair/female/lightBrown/3.png'
            },
            {
                id:'4',
                src:'~@/assets/Textures/Hair/female/lightBrown/4.png'
            },
            {
                id:'5',
                src:'~@/assets/Textures/Hair/female/lightBrown/5.png'
            },
            {
                id:'6',
                src:'~@/assets/Textures/Hair/female/lightBrown/6.png'
            },
            {
                id:'7',
                src:'~@/assets/Textures/Hair/female/lightBrown/7.png'
            },
            {
                id:'8',
                src:'~@/assets/Textures/Hair/female/lightBrown/8.png'
            },
            {
                id:'9',
                src:'~@/assets/Textures/Hair/female/lightBrown/9.png'
            },
            {
                id:'10',
                src:'~@/assets/Textures/Hair/female/lightBrown/10.png'
            }
        ],
        // Женские красные волосы
        hairRedfemale:[
            {
                id:'1',
                src:'~@/assets/Textures/Hair/female/red/1.png'
            },
            {
                id:'2',
                src:'~@/assets/Textures/Hair/female/red/2.png'
            },
            {
                id:'3',
                src:'~@/assets/Textures/Hair/female/red/3.png'
            },
            {
                id:'4',
                src:'~@/assets/Textures/Hair/female/red/4.png'
            },
            {
                id:'5',
                src:'~@/assets/Textures/Hair/female/red/5.png'
            },
            {
                id:'6',
                src:'~@/assets/Textures/Hair/female/red/6.png'
            },
            {
                id:'7',
                src:'~@/assets/Textures/Hair/female/red/7.png'
            },
            {
                id:'8',
                src:'~@/assets/Textures/Hair/female/red/8.png'
            },
            {
                id:'9',
                src:'~@/assets/Textures/Hair/female/red/9.png'
            },
            {
                id:'10',
                src:'~@/assets/Textures/Hair/female/red/10.png'
            }
        ],
    },
}