export default {
    state: {
        // Женские черные волосы
        hairBlackFemale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/female/black/1.png'),
                posX:368,
                posY:129,
                z:9
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/female/black/2.png'),
                posX:415,
                posY:126,
                z:9
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/female/black/3.png'),
                posX:390,
                posY:123,
                z:9
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/female/black/4.png'),
                posX:401,
                posY:107,
                z:9
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/female/black/5.png'),
                posX:419,
                posY:130,
                z:9
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/female/black/6.png'),
                posX:414,
                posY:130,
                z:9
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/female/black/7.png'),
                posX:404,
                posY:110,
                z:9
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/female/black/8.png'),
                posX:415,
                posY:130,
                z:9
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/female/black/9.png'),
                posX:429,
                posY:109,
                z:9
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/female/black/10.png'),
                posX:407,
                posY:125,
                z:9
            }
        ],
        // Женские  бордовые волосы
        hairBordoFemale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/female/bordo/1.png'),
                posX:368,
                posY:129,
                z:9
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/female/bordo/2.png'),
                posX:415,
                posY:126,
                z:9
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/female/bordo/3.png'),
                posX:390,
                posY:123,
                z:9
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/female/bordo/4.png'),
                posX:401,
                posY:107,
                z:9
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/female/bordo/5.png'),
                posX:419,
                posY:130,
                z:9
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/female/bordo/6.png'),
                posX:414,
                posY:130,
                z:9
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/female/bordo/7.png'),
                posX:404,
                posY:110,
                z:9
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/female/bordo/8.png'),
                posX:415,
                posY:130,
                z:9
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/female/bordo/9.png'),
                posX:429,
                posY:109,
                z:9
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/female/bordo/10.png'),
                posX:407,
                posY:125,
                z:9
            }
        ],
        // Женские коричнивые волосы
        hairBrownFemale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/female/brown/1.png'),
                posX:368,
                posY:129,
                z:9
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/female/brown/2.png'),
                posX:415,
                posY:126,
                z:9
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/female/brown/3.png'),
                posX:390,
                posY:123,
                z:9
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/female/brown/4.png'),
                posX:401,
                posY:107,
                z:9
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/female/brown/5.png'),
                posX:419,
                posY:130,
                z:9
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/female/brown/6.png'),
                posX:414,
                posY:130,
                z:9
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/female/brown/7.png'),
                posX:404,
                posY:110,
                z:9
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/female/brown/8.png'),
                posX:415,
                posY:130,
                z:9
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/female/brown/9.png'),
                posX:429,
                posY:109,
                z:9
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/female/brown/10.png'),
                posX:407,
                posY:125,
                z:9
            }
        ],
        // Женские рыжие волосы
        hairGingerFemale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/female/ginger/1.png'),
                posX:368,
                posY:129,
                z:9
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/female/ginger/2.png'),
                posX:415,
                posY:126,
                z:9
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/female/ginger/3.png'),
                posX:390,
                posY:123,
                z:9
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/female/ginger/4.png'),
                posX:401,
                posY:107,
                z:9
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/female/ginger/5.png'),
                posX:419,
                posY:130,
                z:9
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/female/ginger/6.png'),
                posX:414,
                posY:130,
                z:9
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/female/ginger/7.png'),
                posX:404,
                posY:110,
                z:9
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/female/ginger/8.png'),
                posX:415,
                posY:130,
                z:9
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/female/ginger/9.png'),
                posX:429,
                posY:109,
                z:9
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/female/ginger/10.png'),
                posX:407,
                posY:125,
                z:9
            }
        ],
        // Женские зеленые волосы
        hairGreenFemale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/female/green/1.png'),
                posX:368,
                posY:129,
                z:9
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/female/green/2.png'),
                posX:415,
                posY:126,
                z:9
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/female/green/3.png'),
                posX:390,
                posY:123,
                z:9
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/female/green/4.png'),
                posX:401,
                posY:107,
                z:9
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/female/green/5.png'),
                posX:419,
                posY:130,
                z:9
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/female/green/6.png'),
                posX:414,
                posY:130,
                z:9
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/female/green/7.png'),
                posX:404,
                posY:110,
                z:9
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/female/green/8.png'),
                posX:415,
                posY:130,
                z:9
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/female/green/9.png'),
                posX:429,
                posY:109,
                z:9
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/female/green/10.png'),
                posX:407,
                posY:125,
                z:9
            }
        ],
        // Женские светло-коричнивые волосы
        hairLightBrownFemale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/female/lightBrown/1.png'),
                posX:368,
                posY:129,
                z:9
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/female/lightBrown/2.png'),
                posX:415,
                posY:126,
                z:9
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/female/lightBrown/3.png'),
                posX:390,
                posY:123,
                z:9
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/female/lightBrown/4.png'),
                posX:401,
                posY:107,
                z:9
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/female/lightBrown/5.png'),
                posX:419,
                posY:130,
                z:9
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/female/lightBrown/6.png'),
                posX:414,
                posY:130,
                z:9
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/female/lightBrown/7.png'),
                posX:404,
                posY:110,
                z:9
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/female/lightBrown/8.png'),
                posX:415,
                posY:130,
                z:9
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/female/lightBrown/9.png'),
                posX:429,
                posY:109,
                z:9
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/female/lightBrown/10.png'),
                posX:407,
                posY:125,
                z:9
            }
        ],
        // Женские красные волосы
        hairRedFemale:[
            {
                id:'1',
                src:require('../../assets/Textures/Hair/female/red/1.png'),
                posX:368,
                posY:129,
                z:9
            },
            {
                id:'2',
                src:require('../../assets/Textures/Hair/female/red/2.png'),
                posX:415,
                posY:126,
                z:9
            },
            {
                id:'3',
                src:require('../../assets/Textures/Hair/female/red/3.png'),
                posX:390,
                posY:123,
                z:9
            },
            {
                id:'4',
                src:require('../../assets/Textures/Hair/female/red/4.png'),
                posX:401,
                posY:107,
                z:9
            },
            {
                id:'5',
                src:require('../../assets/Textures/Hair/female/red/5.png'),
                posX:419,
                posY:130,
                z:9
            },
            {
                id:'6',
                src:require('../../assets/Textures/Hair/female/red/6.png'),
                posX:414,
                posY:130,
                z:9
            },
            {
                id:'7',
                src:require('../../assets/Textures/Hair/female/red/7.png'),
                posX:404,
                posY:110,
                z:9
            },
            {
                id:'8',
                src:require('../../assets/Textures/Hair/female/red/8.png'),
                posX:415,
                posY:130,
                z:9
            },
            {
                id:'9',
                src:require('../../assets/Textures/Hair/female/red/9.png'),
                posX:429,
                posY:109,
                z:9
            },
            {
                id:'10',
                src:require('../../assets/Textures/Hair/female/red/10.png'),
                posX:407,
                posY:125,
                z:9
            }
        ],
    },
}