export default {
    state: {
        pantsMale: [
            {
                id:1,
                src:require('../../assets/Textures/Pants/male/1.png'),
                posX:420,
                posY:580,
                z:4
            },
            {
                id:2,
                src:require('../../assets/Textures/Pants/male/2.png'),
                posX:406,
                posY:580,
                z:6
            },
            {
                id:3,
                src:require('../../assets/Textures/Pants/male/3.png'),
                posX:415,
                posY:580,
                z:4
            },
            {
                id:4,
                src:require('../../assets/Textures/Pants/male/4.png'),
                posX:424,
                posY:580,
                z:4
            },
            {
                id:5,
                src:require('../../assets/Textures/Pants/male/5.png'),
                posX:425,
                posY:580,
                z:4
            },
            {
                id:6,
                src:require('../../assets/Textures/Pants/male/6.png'),
                posX:423,
                posY:582,
                z:4
            },
            {
                id:7,
                src:require('../../assets/Textures/Pants/male/7.png'),
                posX:423,
                posY:582,
                z:4
            },
            {
                id:8,
                src:require('../../assets/Textures/Pants/male/8.png'),
                posX:425,
                posY:583,
                z:4
            },
            {
                id:9,
                src:require('../../assets/Textures/Pants/male/9.png'),
                posX:425,
                posY:580,
                z:4
            },
            {
                id:10,
                src:require('../../assets/Textures/Pants/male/10.png'),
                posX:424,
                posY:580,
                z:4
            },
        ],
        pantsFemale: [
            {
                id:1,
                src:require('../../assets/Textures/Pants/female/1.png'),
                posX:405,
                posY:545,
                z:6
            },
            {
                id:2,
                src:require('../../assets/Textures/Pants/female/2.png'),
                posX:425,
                posY:540,
                z:6
            },
            {
                id:3,
                src:require('../../assets/Textures/Pants/female/3.png'),
                posX:413,
                posY:540,
                z:4
            },
            {
                id:4,
                src:require('../../assets/Textures/Pants/female/4.png'),
                posX:425,
                posY:540,
                z:4
            },
            {
                id:5,
                src:require('../../assets/Textures/Pants/female/5.png'),
                posX:393,
                posY:540,
                z:6
            },
            {
                id:6,
                src:require('../../assets/Textures/Pants/female/6.png'),
                posX:401,
                posY:520,
                z:4
            },
            {
                id:7,
                src:require('../../assets/Textures/Pants/female/7.png'),
                posX:424,
                posY:545,
                z:4
            },
            {
                id:8,
                src:require('../../assets/Textures/Pants/female/8.png'),
                posX:410,
                posY:525,
                z:4
            },
            {
                id:9,
                src:require('../../assets/Textures/Pants/female/9.png'),
                posX:415,
                posY:560,
                z:4
            },
            {
                id:10,
                src:require('../../assets/Textures/Pants/female/10.png'),
                posX:425,
                posY:530,
                z:4
            },
            {
                id:11,
                src:require('../../assets/Textures/Pants/female/11.png'),
                posX:424,
                posY:525,
                z:4
            },
            {
                id:12,
                src:require('../../assets/Textures/Pants/female/12.png'),
                posX:426,
                posY:548,
                z:4
            },
            {
                id:13,
                src:require('../../assets/Textures/Pants/female/13.png'),
                posX:424,
                posY:537,
                z:4
            },
            {
                id:14,
                src:require('../../assets/Textures/Pants/female/14.png'),
                posX:415,
                posY:530,
                z:4
            },
            {
                id:15,
                src:require('../../assets/Textures/Pants/female/15.png'),
                posX:415,
                posY:530,
                z:4
            },
        ],
        pantsMaleDisableMap:[
            {
                disable: []
            },
            {
                disable: [100] 
            },
            {
                disable: [100] 
            },
            {
                disable: [100] 
            },
            {
                disable: [100]  
            },
            {
                disable: [100] 
            },
            {
                disable: [100]   
            },
            {
                disable: [100] 
            },
            {
                disable: [100] 
            },
            {
                disable: [100] 
            },
            {
                disable: [100] 
            },
        ]
    }
}