export default {
    state: {
        shirtsMale: [
            {
                id:1,
                src:require('../../assets/Textures/Shirts/male/1.png'),
                posX:200,
                posY:200
            },
            {
                id:2,
                src:require('../../assets/Textures/Shirts/male/2.png'),
                posX:200,
                posY:200
            },
            {
                id:3,
                src:require('../../assets/Textures/Shirts/male/3.png'),
                posX:200,
                posY:200
            },
            {
                id:4,
                src:require('../../assets/Textures/Shirts/male/4.png'),
                posX:200,
                posY:200
            },
            {
                id:5,
                src:require('../../assets/Textures/Shirts/male/5.png'),
                posX:200,
                posY:200
            },
            {
                id:6,
                src:require('../../assets/Textures/Shirts/male/6.png'),
                posX:200,
                posY:200
            },
            {
                id:7,
                src:require('../../assets/Textures/Shirts/male/7.png'),
                posX:200,
                posY:200
            },
            {
                id:8,
                src:require('../../assets/Textures/Shirts/male/8.png'),
                posX:200,
                posY:200
            },
            {
                id:9,
                src:require('../../assets/Textures/Shirts/male/9.png'),
                posX:200,
                posY:200
            },
            {
                id:10,
                src:require('../../assets/Textures/Shirts/male/10.png'),
                posX:200,
                posY:200
            },
        ],
        shirtsFemale: [
            {
                id:1,
                src:require('../../assets/Textures/Shirts/female/1.png'),
                posX:200,
                posY:200
            },
            {
                id:2,
                src:require('../../assets/Textures/Shirts/female/2.png'),
                posX:200,
                posY:200
            },
            {
                id:3,
                src:require('../../assets/Textures/Shirts/female/3.png'),
                posX:200,
                posY:200
            },
            {
                id:4,
                src:require('../../assets/Textures/Shirts/female/4.png'),
                posX:200,
                posY:200
            },
            {
                id:5,
                src:require('../../assets/Textures/Shirts/female/5.png'),
                posX:200,
                posY:200
            },
            {
                id:6,
                src:require('../../assets/Textures/Shirts/female/6.png'),
                posX:200,
                posY:200
            },
            {
                id:7,
                src:require('../../assets/Textures/Shirts/female/7.png'),
                posX:200,
                posY:200
            },
            {
                id:8,
                src:require('../../assets/Textures/Shirts/female/8.png'),
                posX:200,
                posY:200
            },
            {
                id:9,
                src:require('../../assets/Textures/Shirts/female/9.png'),
                posX:200,
                posY:200
            },
            {
                id:10,
                src:require('../../assets/Textures/Shirts/female/10.png'),
                posX:200,
                posY:200
            },
        ],
    }
}