export default {
    state: {
        shoesMale: [
            {
                id:1,
                src:require('../../assets/Textures/Shoes/male/1.png'),
                icon:require('../../assets/Textures/Shoes/male/icons/1.png'),
                posX:200,
                posY:200
            },
            {
                id:2,
                src:require('../../assets/Textures/Shoes/male/2.png'),
                icon:require('../../assets/Textures/Shoes/male/icons/2.png'),
                posX:200,
                posY:200
            },
            {
                id:3,
                src:require('../../assets/Textures/Shoes/male/3.png'),
                icon:require('../../assets/Textures/Shoes/male/icons/2.png'),
                posX:200,
                posY:200
            },
            {
                id:4,
                src:require('../../assets/Textures/Shoes/male/4.png'),
                icon:require('../../assets/Textures/Shoes/male/icons/4.png'),
                posX:200,
                posY:200
            },
            {
                id:5,
                src:require('../../assets/Textures/Shoes/male/5.png'),
                icon:require('../../assets/Textures/Shoes/male/icons/5.png'),
                posX:200,
                posY:200
            },
            {
                id:6,
                src:require('../../assets/Textures/Shoes/male/6.png'),
                icon:require('../../assets/Textures/Shoes/male/icons/6.png'),
                posX:200,
                posY:200
            },
            {
                id:7,
                src:require('../../assets/Textures/Shoes/male/7.png'),
                icon:require('../../assets/Textures/Shoes/male/icons/7.png'),
                posX:200,
                posY:200
            },
            {
                id:8,
                src:require('../../assets/Textures/Shoes/male/8.png'),
                icon:require('../../assets/Textures/Shoes/male/icons/8.png'),
                posX:200,
                posY:200
            },
        ],
        shoesFemale: [
            {
                id:1,
                src:require('../../assets/Textures/Shoes/female/1.png'),
                icon:require('../../assets/Textures/Shoes/female/icons/1.png'),
                posX:200,
                posY:200
            },
            {
                id:2,
                src:require('../../assets/Textures/Shoes/female/2.png'),
                icon:require('../../assets/Textures/Shoes/female/icons/2.png'),
                posX:200,
                posY:200
            },
            {
                id:3,
                src:require('../../assets/Textures/Shoes/female/3.png'),
                icon:require('../../assets/Textures/Shoes/female/icons/3.png'),
                posX:200,
                posY:200
            },
            {
                id:4,
                src:require('../../assets/Textures/Shoes/female/4.png'),
                icon:require('../../assets/Textures/Shoes/female/icons/4.png'),
                posX:200,
                posY:200
            },
            {
                id:5,
                src:require('../../assets/Textures/Shoes/female/5.png'),
                icon:require('../../assets/Textures/Shoes/female/icons/5.png'),
                posX:200,
                posY:200
            },
            {
                id:6,
                src:require('../../assets/Textures/Shoes/female/6.png'),
                icon:require('../../assets/Textures/Shoes/female/icons/6.png'),
                posX:200,
                posY:200
            },
            {
                id:7,
                src:require('../../assets/Textures/Shoes/female/7.png'),
                icon:require('../../assets/Textures/Shoes/female/icons/7.png'),
                posX:200,
                posY:200
            },
            {
                id:8,
                src:require('../../assets/Textures/Shoes/female/8.png'),
                icon:require('../../assets/Textures/Shoes/female/icons/8.png'),
                posX:200,
                posY:200
            },
        ],
    }
}